server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Habilita compresión GZIP
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Intenta cargar el archivo, si no, carga el index.html (SPA Fallback)
        try_files $uri $uri/ /index.html;
    }

    # Caché estática para assets
    location ~* \.(?:ico|css|js|map|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|otf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
